### ISSUE TITLE
which engine to use?

### ISSUE THREAD

**Issue by johannesbottcher** [darwiin/awesome-neue-latex-cv#1]
http://tex.stackexchange.com/q/347857/37907

Please see my comment below the question.

**Comment by darwiin** [comment]
I know the name is not very original, but this template use Font Awesome, Source Font and is for CV... So, Awesome Source CV...

I tried to reproduce, but didn't have the issue on my environment (Working on MacOS with MacTex distribution).

Could you please give me more informations about your environment. Which version of the Font Awesome package are you using ? Which Version of the font is installed on your system?

**Comment by darwiin** [comment]
Latest release use Luatex engine.
