### ISSUE TITLE
Modifications of this template

### ISSUE THREAD

**Issue by Garret** [darwiin/awesome-neue-latex-cv#2]
I am sorry but I could not find another way to contact you and github does not allow anymore private messaging. I hope you will visualize this post. 

The template is really beautiful but I have two requests to make it more personalized for my situation. I would like to have two sections on the same line, like for example "Languages" and "Strengths". Do you know how could I achieve that? I am doing this because I think the language section has too much empty space on the right that I would like to avoid.

Then I am not good with tables and my plan was to have three reference contacts than two. Do you know the latex code to obtain that?

I have attached a picture to better explain my requests.

Thank you very much in advance.

![Example of the final result](https://cloud.githubusercontent.com/assets/27555/25896794/e4152344-3585-11e7-89d3-1d4e5bdca03f.png)

**Comment by darwiin** [comment]
Hi Garret,

Thanks for your interest. I think it's a good suggestion, I will update the template this week.

**Comment by johannesbottcher** [comment]
Crosslink: [How to modify a CV template freely available on Github](https://tex.stackexchange.com/q/368968/37907)

**Comment by darwiin** [comment]
Hi @Garret 
I have just pushed a way to solve your issue with your strength section. 

`
\twocolumnsection
{\sectionTitle{Langues}{\faLanguage}
\begin{skills}
	\skill{Français}{5}
	\skill{Anglais}{4}
\end{skills}}
{\sectionTitle{Forces}{\faThumbsUp}
\vspace{1em}
\begin{itemize}
	\item Autonomie                       
    \item Prise d'initiative                    
    \item Ponctuel                                                                  
\end{itemize}
}
`
[cv.pdf](https://github.com/darwiin/awesome-neue-latex-cv/files/1012390/cv.pdf)

**Comment by Garret** [comment]
Thank you very much. It works nice. However, may I please also ask you to share the references code section where you have three names?

**Comment by darwiin** [comment]
@Garret =>https://gist.github.com/darwiin/8fbd1d4661b7db61fc8d277211f84f49
